# Generated by Django 5.0.7 on 2024-07-24 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landlord_id_scan', models.ImageField(default='LandlordIdScan', upload_to='landlord_id_scans/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('type_of_user', models.CharField(choices=[('landlord', 'Landlord'), ('tenant', 'Tenant'), ('admin', 'Administrator')], default='tenant', max_length=20)),
                ('phone', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('no_of_rooms', models.IntegerField()),
                ('amenities', models.TextField()),
                ('apartment_main_img', models.ImageField(default='Homi', upload_to='apartment_images/')),
                ('landlord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='allfunctions.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_bedrooms', models.IntegerField()),
                ('size_in_sq_meters', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('occupied', models.BooleanField(default=False)),
                ('room_images', models.ImageField(default='Homi rooms', upload_to='room_images/')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='allfunctions.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id_scan', models.ImageField(default='TenantIdScan', upload_to='tenant_id_scans/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to='allfunctions.user')),
            ],
        ),
        migrations.AddField(
            model_name='landlord',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_profile', to='allfunctions.user'),
        ),
    ]
