# Generated by Django 5.0.7 on 2024-07-24 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allfunctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='landlord',
            field=models.ForeignKey(limit_choices_to={'user__type_of_user': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='allfunctions.landlord'),
        ),
    ]
