# Generated by Django 5.0.7 on 2024-07-24 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allfunctions', '0002_alter_apartment_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='rent_date',
            field=models.DateField(default=datetime.date(2024, 7, 24)),
        ),
    ]
