# Generated by Django 5.0.7 on 2024-07-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allfunctions', '0004_room_entry_date_alter_apartment_rent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
