# Generated by Django 5.0.7 on 2024-07-24 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allfunctions', '0007_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='tag',
            field=models.CharField(choices=[('noise', 'Noise'), ('repair', 'Repair'), ('service', 'Service')], default='No issue', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date_field',
            field=models.DateField(verbose_name=datetime.datetime(2024, 7, 24, 9, 34, 51, 383175, tzinfo=datetime.timezone.utc)),
        ),
    ]
