# Generated by Django 5.0.7 on 2024-07-24 09:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allfunctions', '0008_complaint_tag_alter_complaint_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_occupying', to='allfunctions.user'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date_field',
            field=models.DateField(verbose_name=datetime.datetime(2024, 7, 24, 9, 45, 56, 15704, tzinfo=datetime.timezone.utc)),
        ),
    ]
