# Generated by Django 5.0.7 on 2024-07-30 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allfunctions', '0010_remove_room_room_images_alter_complaint_date_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='rent_date',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date_field',
            field=models.DateField(verbose_name=datetime.datetime(2024, 7, 30, 9, 48, 33, 303272, tzinfo=datetime.timezone.utc)),
        ),
    ]
