# Generated by Django 5.0.7 on 2024-07-31 09:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allfunctions', '0013_alter_complaint_date_field_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='allfunctions.tenant'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date_field',
            field=models.DateField(verbose_name=datetime.datetime(2024, 7, 31, 9, 39, 19, 864835, tzinfo=datetime.timezone.utc)),
        ),
    ]
