# Generated by Django 5.0.7 on 2024-07-31 09:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allfunctions', '0014_alter_comment_tenant_alter_complaint_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='apartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='allfunctions.apartment'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date_field',
            field=models.DateField(verbose_name=datetime.datetime(2024, 7, 31, 9, 51, 44, 145730, tzinfo=datetime.timezone.utc)),
        ),
    ]
