# Generated by Django 5.0.7 on 2024-07-31 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allfunctions', '0015_tenant_apartment_alter_complaint_date_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='apartment',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date_field',
            field=models.DateField(verbose_name=datetime.datetime(2024, 7, 31, 9, 55, 33, 742896, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
