# Generated by Django 5.0.7 on 2024-07-31 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allfunctions', '0016_remove_tenant_apartment_alter_complaint_date_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_field',
            field=models.DateField(verbose_name=datetime.datetime(2024, 7, 31, 10, 59, 42, 37752, tzinfo=datetime.timezone.utc)),
        ),
    ]
