# Generated by Django 5.0.7 on 2024-07-31 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allfunctions', '0018_alter_complaint_date_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_field',
            field=models.DateField(verbose_name=datetime.datetime(2024, 7, 31, 11, 37, 42, 183168, tzinfo=datetime.timezone.utc)),
        ),
    ]
